title: 최시민의 기술 블로그
description: 기술 지식을 기록합니다.

author:
  name: 최시민
  email: choesimin961009@gmail.com

collections:
  notes:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed