title: SIMIN

author:
  name: 최시민
  email: choesimin961009@gmail.com

collections:
  skills:
    output: true
  graphics:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed