title: 시미니
description: Personal Blog

author:
  name: 최시민
  email: choesimin961009@gmail.com

collections:
  pages:
    output: true
  notes:
    output: true
  arts:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed