title: 시민이의 개인 블로그
description: 시민이의 개인 블로그입니다. 

author:
  name: 최시민
  email: choesimin961009@gmail.com

collections:
  pages:
    output: true
  notes:
    output: true
  arts:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed